update public.exercises set image_url = '/catalog-images/abdominales.png' where name = 'Abdominales';
update public.exercises set image_url = '/catalog-images/abductores.png' where name = 'Abductores';
update public.exercises set image_url = '/catalog-images/aductores.png' where name = 'Aductores';
update public.exercises set image_url = '/catalog-images/aperturas-pecho.png' where name = 'Aperturas de pecho';
update public.exercises set image_url = '/catalog-images/bicicleta-reclinada.png' where name = 'Bicicleta reclinada';
update public.exercises set image_url = '/catalog-images/caminata-cinta.png' where name = 'Caminata en cinta';
update public.exercises set image_url = '/catalog-images/curl-femoral.png' where name = 'Curl femoral';
update public.exercises set image_url = '/catalog-images/dominadas-asistidas.png' where name = 'Dominadas asistidas';
update public.exercises set image_url = '/catalog-images/elevacion-gemelos.png' where name = 'Elevación de gemelos de pie';
update public.exercises set image_url = '/catalog-images/eliptica.png' where name = 'Elíptica';
update public.exercises set image_url = '/catalog-images/extension-piernas.png' where name = 'Extensión de piernas';
update public.exercises set image_url = '/catalog-images/extension-triceps.png' where name = 'Extensión de tríceps en polea';
update public.exercises set image_url = '/catalog-images/extension-lumbar.png' where name = 'Extensión lumbar';
update public.exercises set image_url = '/catalog-images/fondos-asistidos.png' where name = 'Fondos asistidos';
update public.exercises set image_url = '/catalog-images/fondos-triceps.png' where name = 'Fondos de tríceps';
update public.exercises set image_url = '/catalog-images/patada-gluteo.png' where name = 'Patada de glúteo';
update public.exercises set image_url = '/catalog-images/press-banca-mancuernas.png' where name = 'Press de banca con mancuernas';
update public.exercises set image_url = '/catalog-images/press-hombros.png' where name = 'Press de hombros';
update public.exercises set image_url = '/catalog-images/remo-trx.png' where name = 'Remo en TRX';
update public.exercises set image_url = '/catalog-images/remo-sentado.png' where name = 'Remo sentado en polea';
update public.exercises set image_url = '/catalog-images/sentadilla-barra.png' where name = 'Sentadilla con barra';
update public.exercises set image_url = '/catalog-images/sentadilla-goblet.png' where name = 'Sentadilla goblet con mancuerna';
update public.exercises set image_url = '/catalog-images/subida-cajon.png' where name = 'Subida al cajón';
