import { DecimalPipe } from '@angular/common';
import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { form, FormField } from '@angular/forms/signals';
import { RouterLink } from '@angular/router';

import { type StatisticsOverview, StatisticsService } from './statistics.service';

@Component({
  selector: 'app-statistics-page', standalone: true, imports: [DecimalPipe, FormField, RouterLink],
  template: `
    <main class="page"><header class="hero"><div><p class="eyebrow">ESTADÍSTICAS</p><h1>Tu entrenamiento en cifras.</h1><p class="lede">Todos los valores se calculan a partir de tu historial de entrenamientos.</p></div><a routerLink="/history">Ver historial</a></header>
      <form class="card filters" (submit)="onSubmit($event)" aria-label="Filtrar estadísticas por fecha"><label><span>Desde</span><input type="date" [formField]="dateRangeForm.from" /></label><label><span>Hasta</span><input type="date" [formField]="dateRangeForm.to" /></label><button type="submit" [disabled]="loading()">Aplicar fechas</button><button type="button" (click)="clearDates()" [disabled]="loading()">Limpiar</button></form>
      @if (error(); as message) { <p class="banner error" role="alert">{{ message }}</p> }
      @if (loading()) { <section class="card state" aria-live="polite"><p>Calculando estadísticas…</p></section> } @else if (overview(); as data) { @if (data.workoutCount === 0) { <section class="card state"><h2>Todavía no hay estadísticas.</h2><p>Completa un entrenamiento para generar estos datos.</p><a class="primary" routerLink="/workouts/start">Iniciar entrenamiento</a></section> } @else { <section class="metrics" aria-label="Totales de entrenamiento"><article class="card"><span>Entrenamientos</span><strong>{{ data.workoutCount }}</strong></article><article class="card"><span>Frecuencia</span><strong>{{ data.workoutFrequencyPerWeek | number:'1.1-1' }}/semana</strong></article><article class="card"><span>Volumen de fuerza</span><strong>{{ data.strengthVolume | number:'1.0-0' }}</strong></article><article class="card"><span>Duración de cardio</span><strong>{{ formatDuration(data.cardioDurationSeconds) }}</strong></article><article class="card"><span>Distancia de cardio</span><strong>{{ data.cardioDistance | number:'1.0-2' }}</strong></article></section>
        <section class="layout"><section class="card"><h2>Volumen de fuerza trend</h2><div class="trend" role="img" aria-label="Volumen de fuerza by workout date">@for (point of data.volumeTrend; track point.date) { <div class="trend-row"><span>{{ formatDate(point.date) }}</span><div class="bar-track"><div class="bar" [style.width.%]="trendWidth(point.volume)"></div></div><strong>{{ point.volume | number:'1.0-0' }}</strong></div> } @empty { <p>No hay volumen de fuerza registrado en este periodo.</p> }</div></section>
          <section class="card"><h2>Grupos musculares</h2><ul>@for (group of data.muscleGroups; track group.name) { <li><span>{{ group.name }}</span><strong>{{ group.exercises }}</strong></li> } @empty { <li>Sin grupos musculares registrados in this range.</li> }</ul></section>
          <section class="card"><h2>Mejores resultados</h2><div class="table-wrap"><table><caption class="sr-only">Mejor resultado registrado por ejercicio</caption><thead><tr><th scope="col">Ejercicio</th><th scope="col">Mejor resultado</th></tr></thead><tbody>@for (result of data.bestResults; track result.exerciseId) { <tr><th scope="row">{{ result.exerciseName }}</th><td>{{ result.value | number:'1.0-2' }} {{ result.unit }}</td></tr> } @empty { <tr><td colspan="2">No hay resultados registrados en este periodo.</td></tr> }</tbody></table></div></section></section> } }
    </main>`,
  styles: `:host{display:block;min-height:100vh;background:#f5f1e8;color:#1f3028}.page{padding:2rem clamp(1rem,4vw,4rem) 3rem}.hero,.filters,.layout{display:flex;gap:1rem}.hero{justify-content:space-between;align-items:end;flex-wrap:wrap;margin-bottom:1.5rem}h1{margin:.6rem 0;font-size:clamp(2.4rem,7vw,4.6rem);line-height:.95}.eyebrow{margin:0;color:#a44a2c;font-size:.75rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.lede{color:#435248}.card,.banner{border:1px solid #ded6c7;border-radius:1.2rem;background:#fffdf8;padding:1.2rem}.filters{align-items:end;flex-wrap:wrap;margin-bottom:1rem}label{display:grid;gap:.35rem;font-weight:700}input{border:1px solid #c8bca7;border-radius:.65rem;padding:.65rem;font:inherit}.metrics{display:grid;gap:1rem;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));margin:1rem 0}.metrics span,.metrics strong{display:block}.metrics strong{margin-top:.45rem;font-size:1.6rem}.layout{align-items:start;flex-wrap:wrap}.layout>section{flex:1 1 19rem}.trend{display:grid;gap:.75rem}.trend-row{display:grid;grid-template-columns:minmax(5.5rem,.8fr) minmax(4rem,2fr) auto;gap:.5rem;align-items:center}.bar-track{height:.75rem;border-radius:99px;background:#ece4d8;overflow:hidden}.bar{height:100%;min-width:2px;background:#a44a2c}ul{list-style:none;padding:0;margin:0;display:grid;gap:.65rem}li{display:flex;justify-content:space-between;gap:1rem;border-bottom:1px solid #ece4d8;padding-bottom:.55rem}table{width:100%;border-collapse:collapse;text-align:left}th,td{padding:.65rem;border-bottom:1px solid #ece4d8}.state{display:grid;gap:.75rem;justify-items:start}.banner{margin-bottom:1rem}.error{color:#9d2f2f}a,button{border:0;border-radius:.75rem;padding:.8rem 1rem;font:inherit;text-decoration:none;cursor:pointer;background:#e8dfd0;color:#1f3028}.primary{background:#1f3028;color:#fff}button:disabled{opacity:.65;cursor:not-allowed}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}`,
})
export class StatisticsPage {
  private readonly statistics = inject(StatisticsService); private readonly destroyRef = inject(DestroyRef);
  protected readonly loading = signal(true); protected readonly error = signal<string | null>(null); protected readonly overview = signal<StatisticsOverview | null>(null); protected readonly maxTrendVolume = computed(() => Math.max(...(this.overview()?.volumeTrend.map((point) => point.volume) ?? [0]), 0));

  protected readonly dateRangeModel = signal({ from: '', to: '' });
  protected readonly dateRangeForm = form(this.dateRangeModel);

  constructor() { this.load(); }

  protected onSubmit(event: Event): void {
    event.preventDefault();
    this.load();
  }

  protected load(): void { this.loading.set(true); this.error.set(null); const subscription = this.statistics.getOverview({ from: this.dateRangeModel().from || null, to: this.dateRangeModel().to || null }).subscribe({ next: (overview) => { this.overview.set(overview); this.loading.set(false); }, error: (error: unknown) => { this.error.set(error instanceof Error && error.message ? error.message : 'We could not calculate your statistics.'); this.loading.set(false); } }); this.destroyRef.onDestroy(() => subscription.unsubscribe()); }
  protected clearDates(): void { this.dateRangeModel.set({ from: '', to: '' }); this.load(); } protected trendWidth(value: number): number { const max = this.maxTrendVolume(); return max === 0 ? 0 : (value / max) * 100; } protected formatDuration(seconds: number): string { const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`; } protected formatDate(value: string): string { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(`${value}T00:00:00`)); }
}
